### ISSUE TITLE
file rearrangement broke config tests

### ISSUE THREAD

**Issue by tsgouros** [ivlab/MinVR2#117] opened 2017-02-20 02:07 UTC
The wholesale rearrangement of the tests DanK made has broken the config tests in some fashion. They were set up so that 'make test' ran a whole raft of unit tests for the data index and queue using the cmake-supplied testing framework. The move into the test-batch directory has broken them somehow. 

I'm not going to have a chance to work on this until Tuesday or Wednesday, but thought I'd mention it, and ask that if we're going to rearrange to have a directory for batch test and for interactive tests, can we arrange them so they are one 'tests' directory with 'batch' and 'interactive' in it? Better yet, since there are real names the software industry uses for these kinds of tests I would use those names, and do something like this:

 tests/unit 
 tests/system or tests/integration

The other thing about these kinds of file rearrangements is that they break the file history that you get from git. So it's more challenging than it needs to be for me to figure out what changed to break this functionality because I can't use git diff to figure it out. I don't think anything's wrong with some slight irrationalities in the way the directories are arranged.

**Comment by dankeefe** [comment] 2017-02-20 03:29
Sorry about that Tom.  I don't mind debugging it now that I know there is an issue.  I did not try running the tests because there does not seem to be a target generated for them when using Xcode.  Do the tests only work on Linux?  Perhaps if I do a separate Makefile-based build on OSX it will be possible to run them.  I will try that.

It's possible that I missed some files and ended up accidentally adding rather than moving, but in general I tried to use git mv to move files around thinking that the history would be preserved in this situation.  You seem to be saying that I made this harder for you than it needed to be.  Can you suggest a better way to do this or is it that maybe I accidentally missed this for a key file?

We can adjust the naming and/or directory organization if a good case can be made for that.  In general I'm all for standard software development names, but I think the most important distinction for users here will be to know which tests can be run in an automated batch mode vs. which ones are interactive graphics.  Unit/system/integration doesn't exactly convey this -- I guess system would be the interactive category for the most part, but there could be system-level tests (like an automated client-server networking test across multiple nodes without graphics) that run in batch mode.  For the batch mode, my vision would be that at some point we get these setup to run in a nightly test suite.  For the interactive, these are the ones that users might be more interested in running when setting up a new VR display.  These are issues that we can continue to discuss and tweak as we get more into testing.  The major accomplishment in this pull was for the first time to get the examples out of the repo and leave only tests of one sort or another.

**Comment by tsgouros** [comment] 2017-02-20 04:02
I don't use XCode (yet), just gcc/make. I don't know how cmake works with XCode. All I know is that there is a 'make test' target that cmake produces that runs a whole ensemble of unit tests I wrote for the config stuff. I imagine this is the germ of exactly that kind of nightly test suite, but maybe there's some better way. 

If you don't see a 'test' build target with XCode, do you see a 'ctest' binary somewhere? I can run these tests with either command. And yes, if you do a gcc/make build on OSX, you should see these, since that's what I do.

I don't know about git mv, just that when I do a git log on the unit test code or on the CMakeLists.txt files (what I was doing to try to figure out what broke) I only get one entry. There used to be a RunSomeIndexTests binary that was created, but I don't know what happened to it. I suppose that's probably the test-dataindex binary now.

Also, what happened to the MVRLookup binary? That was meant to be part of the MinVR release, even if it hasn't seemed that important yet.

**Comment by bretjackson** [comment] 2017-02-20 15:17
Dan,
In Xcode you can change the target at the top from all_build to
"RUN_TESTS". It should then run the ctests when you build. For me it failed
with the following error:

PhaseScriptExecution CMake\ PostBuild\ Rules
build/MinVR_Project.build/Debug/RUN_TESTS.build/Script-BB1C37630716435DB40BA57D.sh

    cd /Volumes/BOOTCAMP/vis/sw/user-checkouts/bjackson/src/minvr2

    /bin/sh -c
/Volumes/BOOTCAMP/vis/sw/user-checkouts/bjackson/src/minvr2/build/MinVR_Project.build/Debug/RUN_TESTS.build/Script-BB1C37630716435DB40BA57D.sh


/Applications/CMake.app/Contents/bin/ctest --force-new-ctest-process -C
Debug

Test project
/Volumes/BOOTCAMP/vis/sw/user-checkouts/bjackson/src/minvr2/build

      Start  1: test_datum_1

 1/23 Test  #1: test_datum_1 .....................***Not Run   0.00 sec

      Start  2: test_datum_2

 2/23 Test  #2: test_datum_2 .....................***Not Run   0.00 sec

      Start  3: test_datum_3

 3/23 Test  #3: test_datum_3 .....................***Not Run   0.00 sec

      Start  4: test_datum_4

 4/23 Test  #4: test_datum_4 .....................***Not Run   0.00 sec

      Start  5: test_datum_5

 5/23 Test  #5: test_datum_5 .....................***Not Run   0.00 sec

      Start  6: test_datum_6

 6/23 Test  #6: test_datum_6 .....................***Not Run   0.00 sec

      Start  7: test_datum_7

 7/23 Test  #7: test_datum_7 .....................***Not Run   0.00 sec

      Start  8: test_datum_8

 8/23 Test  #8: test_datum_8 .....................***Not Run   0.00 sec

      Start  9: test_datum_9

 9/23 Test  #9: test_datum_9 .....................***Not Run   0.00 sec

      Start 10: test_datum_10

10/23 Test #10: test_datum_10 ....................***Not Run   0.00 sec

      Start 11: test_index_1

11/23 Test #11: test_index_1 .....................***Not Run   0.00 sec

      Start 12: test_index_2

12/23 Test #12: test_index_2 .....................***Not Run   0.00 sec

      Start 13: test_index_3

13/23 Test #13: test_index_3 .....................***Not Run   0.00 sec

      Start 14: test_index_4

14/23 Test #14: test_index_4 .....................***Not Run   0.00 sec

      Start 15: test_index_5

15/23 Test #15: test_index_5 .....................***Not Run   0.00 sec

      Start 16: test_index_6

16/23 Test #16: test_index_6 .....................***Not Run   0.00 sec

      Start 17: test_index_7

17/23 Test #17: test_index_7 .....................***Not Run   0.00 sec

      Start 18: test_index_8

18/23 Test #18: test_index_8 .....................***Not Run   0.00 sec

      Start 19: test_index_9

19/23 Test #19: test_index_9 .....................***Not Run   0.00 sec

      Start 20: test_index_10

20/23 Test #20: test_index_10 ....................***Not Run   0.00 sec

      Start 21: test_queue_1

21/23 Test #21: test_queue_1 .....................***Not Run   0.00 sec

      Start 22: test_queue_2

22/23 Test #22: test_queue_2 .....................***Not Run   0.00 sec

      Start 23: test_queue_3

23/23 Test #23: test_queue_3 .....................***Not Run   0.00 sec


0% tests passed, 23 tests failed out of 23


Total Test time (real) =   0.04 sec


The following tests FAILED:

  1 - test_datum_1 (BAD_COMMAND)

  2 - test_datum_2 (BAD_COMMAND)

  3 - test_datum_3 (BAD_COMMAND)

  4 - test_datum_4 (BAD_COMMAND)

  5 - test_datum_5 (BAD_COMMAND)

  6 - test_datum_6 (BAD_COMMAND)

  7 - test_datum_7 (BAD_COMMAND)

  8 - test_datum_8 (BAD_COMMAND)

  9 - test_datum_9 (BAD_COMMAND)

10 - test_datum_10 (BAD_COMMAND)

11 - test_index_1 (BAD_COMMAND)

12 - test_index_2 (BAD_COMMAND)

13 - test_index_3 (BAD_COMMAND)

14 - test_index_4 (BAD_COMMAND)

15 - test_index_5 (BAD_COMMAND)

16 - test_index_6 (BAD_COMMAND)

17 - test_index_7 (BAD_COMMAND)

18 - test_index_8 (BAD_COMMAND)

19 - test_index_9 (BAD_COMMAND)

20 - test_index_10 (BAD_COMMAND)

21 - test_queue_1 (BAD_COMMAND)

22 - test_queue_2 (BAD_COMMAND)

23 - test_queue_3 (BAD_COMMAND)

Errors while running CTest

make: *** [RUN_TESTS_buildpart_0] Error 8

Command /bin/sh failed with exit code 2

**Comment by tsgouros** [comment] 2017-02-20 15:26
Yes, that's the failure mode. I think it's because the name of the testing binary was changed from RunSomeIndexTests but not everywhere. My first stab at fixing it didn't work though, so I'm not sure what else changed.

**Comment by dankeefe** [comment] 2017-02-20 16:01
Just submitted a pull request to fix this.  The problem is that it couldn’t fine test.xml because the current working directory changed from tests to tests-batch.  Fixed now.

D

-- 
Daniel Keefe
Associate Professor
Department of Computer Science & Engineering
University of Minnesota
http://www.cs.umn.edu/~keefe

On February 20, 2017 at 9:26:32 AM, tsgouros (notifications@github.com) wrote:

Yes, that's the failure mode. I think it's because the name of the testing binary was changed from RunSomeIndexTests but not everywhere. My first stab at fixing it didn't work though, so I'm not sure what else changed.

**Closed as completed** 2017-02-20 21:35 UTC
